/**
 * Migration: Create Users Table
 * Generated: 2024-12-15T12:00:00.000Z
 *
 * Creates the core users table with:
 * - UUID primary key (auto-generated by PostgreSQL)
 * - Unique email address
 * - Display name
 * - Password hash (for local auth)
 * - Email verification flag
 * - Role-based access control
 * - JSONB metadata field
 * - Created/updated timestamps
 */

import type { Migration } from "db-migrate-ts";
import { z } from "zod";

export default {
  name: "20241215120000_create_users_table",
  timestamp: 20241215120000,
  description: "Initial users table with authentication fields",

  up: async (migrate) => {
    // Create the users table
    migrate.createTable("users", {
      id: {
        schema: z.string().uuid(),
        primaryKey: true,
        default: "gen_random_uuid()",
      },
      email: {
        schema: z.string().email().max(254),
        unique: true,
      },
      displayName: {
        schema: z.string().max(100),
      },
      passwordHash: {
        schema: z.string(),
      },
      isVerified: {
        schema: z.boolean(),
        default: false,
      },
      role: {
        schema: z.enum(["admin", "user", "moderator"]),
        default: "user",
      },
      metadata: {
        schema: z.object({}).passthrough(),
        nullable: true,
      },
      createdAt: {
        schema: z.date(),
        default: "NOW()",
      },
      updatedAt: {
        schema: z.date(),
        default: "NOW()",
      },
    });

    // Index for fast email lookups
    migrate.createIndex("users", ["email"], {
      name: "idx_users_email",
      unique: true,
    });

    // Index for role-based queries
    migrate.createIndex("users", ["role"], {
      name: "idx_users_role",
    });

    // UUID-OSSP extension for gen_random_uuid() (PostgreSQL)
    migrate.raw('CREATE EXTENSION IF NOT EXISTS "pgcrypto"');
  },

  down: async (migrate) => {
    migrate.dropIndex("idx_users_role");
    migrate.dropIndex("idx_users_email");
    migrate.dropTable("users" as never);
  },
} satisfies Migration;
